version: '2'
services:
    contratos-app:
        image: contratos
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://contratos-postgresql:5432/contratos
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=contratos-elasticsearch:9300
        ports:
            - 8080:8080
    contratos-postgresql:
        extends:
            file: postgresql.yml
            service: contratos-postgresql
    contratos-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: contratos-elasticsearch
